apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
spec:
  containers:
    - name: gin-demo
      image: {{ .Values.deployment.image }}
      ports:
        - containerPort: {{ .Values.deployment.port }}
          name: http
