apiVersion: v1
kind: Pod
metadata:
  name: gin-demo
  labels:
    app.kubernetes.io/name: gin-demo
spec:
  containers:
    - name: gin-demo
      image: gin-demo:latest
      ports:
        - containerPort: 8080
          name: http
