version: "3.7"

networks:
  backend:
    driver: bridge

services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db
  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    depends_on:
      - mongodb
    ports:
      - 4000:3000
    restart: unless-stopped
    networks:
      - backend
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    expose:
      - 8080
    networks:
      - backend
    depends_on:
      - mongodb_container
volumes:
  mongo_data:
